### ISSUE TITLE
query-string dependency should not be a peerDependency

### ISSUE THREAD

**Issue by jasonk** [pbeshai/serialize-query-params#32]
https://github.com/pbeshai/use-query-params/issues/127

**Comment by pbeshai** [comment]
Addressed via #33 by throwing an exception when the wrong version is present. Available in v1.2.3

**Comment by amireynoso** [comment]
Hey @pbeshai, would you mind explaining your rationale for throwing an exception instead of setting `query-string` to be a dependency? If this library _needs_ `query-string` to function, then it should be added to its dependencies. If it doesn't, why is it listed as a `peerDependency` and/or why would you throw an exception?

I'm not quite sure I understand why the responsibility of installing this supporting library is pushed to the consumers.

Appreciate your work. 🙏

**Comment by pbeshai** [comment]
Hey, thank you for a very politely worded question! The reason why it's a peer dependency and not a direct dependency is that historically some people needed v5 to support older browsers, while some people wanted v6 to work with newer features. I couldn't get the "you choose your version" to work while listing it as a direct dependency, so I let people choose. I do hope in a new version to make this more obvious / use something like the built-in URLSearchParams as a default, but I need to investigate it more still.
